apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secureship-ingress
  namespace: secureship
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: api.secureship.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: secureship-service
                port:
                  number: 80
